---
 - hosts: all
   become: true

   tasks:
    - name: Shotdown only Ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"
    
    
